"""Static sample dataset for the /market/seed-demo-data endpoint.

Job posting `days_ago` values are deliberately chosen so that, once ingested,
`MarketService.update_market_trends` (30-day growth window) produces a mix of
RISING / STABLE / DECLINING jobs, and so that some skills are visibly
concentrated in a few locations only (a shortage signal for the rest).

Hierarchy: 1 Career (industry) -> several Jobs (specific job families) ->
many JobPostings. `job_id`/`career_id` on each posting below are intentionally
NOT hard-coded — MarketService.seed_demo_data() resolves them through the same
_expand_and_resolve heuristic real ingestion uses, so the demo proves the
classification logic actually works instead of just asserting it does.
"""

# Categories use this DB's lowercase ck_skills_category vocabulary
# (technical/data/ai/product/design/business/soft_skill/general) — an
# out-of-band constraint on the live skills table, not part of this
# SQLAlchemy model (Skill.category is a plain string, unconstrained here).
SEED_SKILLS = [
    {"name": "Python", "category": "technical"},
    {"name": "Java", "category": "technical"},
    {"name": "C#", "category": "technical"},
    {"name": "C++", "category": "technical"},
    {"name": "Go", "category": "technical"},
    {"name": "PHP", "category": "technical"},
    {"name": "JavaScript", "category": "technical"},
    {"name": "TypeScript", "category": "technical"},
    {"name": "Node.js", "category": "technical"},
    {"name": "React", "category": "technical"},
    {"name": "HTML/CSS", "category": "technical"},
    {"name": "REST API", "category": "technical"},
    {"name": "Microservices", "category": "technical"},
    {"name": "Git", "category": "technical"},
    {"name": "Linux", "category": "technical"},
    {"name": "SQL", "category": "data"},
    {"name": "PostgreSQL", "category": "data"},
    {"name": "MySQL", "category": "data"},
    {"name": "Docker", "category": "technical"},
    {"name": "Kubernetes", "category": "technical"},
    {"name": "AWS Cloud", "category": "technical"},
    {"name": "Microsoft Azure", "category": "technical"},
    {"name": "Google Cloud Platform", "category": "technical"},
    {"name": "CI/CD", "category": "technical"},
    {"name": "Terraform", "category": "technical"},
    {"name": "Networking", "category": "technical"},
    {"name": "Cybersecurity", "category": "technical"},
    {"name": "Blockchain", "category": "technical"},
    {"name": "Internet of Things", "category": "technical"},
    {"name": "Embedded Systems", "category": "technical"},
    {"name": "PLC", "category": "technical"},
    {"name": "AutoCAD", "category": "technical"},
    {"name": "SolidWorks", "category": "technical"},
    {"name": "Machine Learning", "category": "ai"},
    {"name": "Deep Learning", "category": "ai"},
    {"name": "Natural Language Processing", "category": "ai"},
    {"name": "Computer Vision", "category": "ai"},
    {"name": "Generative AI", "category": "ai"},
    {"name": "MLOps", "category": "ai"},
    {"name": "TensorFlow", "category": "ai"},
    {"name": "PyTorch", "category": "ai"},
    {"name": "Phân tích dữ liệu", "category": "data"},
    {"name": "Thống kê", "category": "data"},
    {"name": "Trực quan hóa dữ liệu", "category": "data"},
    {"name": "ETL", "category": "data"},
    {"name": "Apache Spark", "category": "data"},
    {"name": "Hadoop", "category": "data"},
    {"name": "Power BI", "category": "data"},
    {"name": "Tableau", "category": "data"},
    {"name": "Excel", "category": "business"},
    {"name": "Quản lý sản phẩm", "category": "product"},
    {"name": "Nghiên cứu người dùng", "category": "product"},
    {"name": "Agile/Scrum", "category": "product"},
    {"name": "UX/UI Design", "category": "design"},
    {"name": "Figma", "category": "design"},
    {"name": "Adobe Creative Suite", "category": "design"},
    {"name": "Thiết kế đồ họa", "category": "design"},
    {"name": "Quản lý dự án", "category": "business"},
    {"name": "Phân tích nghiệp vụ", "category": "business"},
    {"name": "Tài chính", "category": "business"},
    {"name": "Kế toán", "category": "business"},
    {"name": "Digital Marketing", "category": "business"},
    {"name": "SEO", "category": "business"},
    {"name": "Bán hàng", "category": "business"},
    {"name": "Logistics", "category": "business"},
    {"name": "Quản lý chuỗi cung ứng", "category": "business"},
    {"name": "Quản trị nhân sự", "category": "business"},
    {"name": "English Communication", "category": "soft_skill"},
    {"name": "Giao tiếp", "category": "soft_skill"},
    {"name": "Làm việc nhóm", "category": "soft_skill"},
    {"name": "Tư duy phản biện", "category": "soft_skill"},
    {"name": "Quản lý thời gian", "category": "soft_skill"},
    {"name": "Lãnh đạo", "category": "soft_skill"},
    {"name": "Thuyết trình", "category": "soft_skill"},
    {"name": "Đàm phán", "category": "soft_skill"},
    {"name": "Sáng tạo", "category": "soft_skill"},
    {"name": "Khả năng thích nghi", "category": "soft_skill"},
    {"name": "Chú ý đến chi tiết", "category": "soft_skill"},
    # General/foundational skills — linked to the Career (industry), not to any
    # one Job, so a beginner posting that only lists these can still be
    # attributed to the right industry via the CareerSkill fallback.
    {"name": "Toán học", "category": "general"},
    {"name": "Giải quyết vấn đề", "category": "general"},
    {"name": "Tư duy logic", "category": "general"},
    {"name": "Nghiên cứu", "category": "general"},
    {"name": "Viết báo cáo", "category": "general"},
    {"name": "Tìm kiếm thông tin", "category": "general"},
    {"name": "Quản lý chất lượng", "category": "general"},
    {"name": "An toàn lao động", "category": "general"},
    {"name": "Chăm sóc khách hàng", "category": "general"},
]

# Rename the original unaccented Vietnamese seed rows in place before
# get_or_create runs. Keeping the same id preserves JobSkill/CareerSkill and
# any student/task/evidence foreign-key references already pointing at them.
SEED_SKILL_RENAMES = {
    "Toan hoc": "Toán học",
    "Giai quyet van de": "Giải quyết vấn đề",
    "Tu duy logic": "Tư duy logic",
}

# Career catalog used by both the market UI and student career
# recommendations. Titles are unique because Career.title has a unique
# constraint; MarketService seeds them with get_or_create semantics so
# repeated calls do not duplicate rows.
SEED_CAREERS = [
    {"title": "Công nghệ thông tin", "description": "Phát triển phần mềm, hệ thống thông tin và giải pháp số."},
    {"title": "Khoa học dữ liệu và trí tuệ nhân tạo", "description": "Phân tích dữ liệu, xây dựng mô hình AI và hỗ trợ ra quyết định."},
    {"title": "An toàn thông tin", "description": "Bảo vệ hệ thống, dữ liệu và hạ tầng trước các rủi ro an ninh mạng."},
    {"title": "Điện toán đám mây", "description": "Thiết kế, vận hành và tối ưu hạ tầng cloud cho doanh nghiệp."},
    {"title": "Điện tử viễn thông", "description": "Phát triển hệ thống điện tử, mạng truyền dẫn và dịch vụ viễn thông."},
    {"title": "Tự động hóa và robot", "description": "Thiết kế hệ thống điều khiển, robot và dây chuyền sản xuất tự động."},
    {"title": "Cơ khí chế tạo", "description": "Thiết kế, gia công và vận hành máy móc trong công nghiệp."},
    {"title": "Kỹ thuật ô tô", "description": "Thiết kế, bảo trì và phát triển công nghệ cho phương tiện giao thông."},
    {"title": "Kỹ thuật điện", "description": "Thiết kế và vận hành hệ thống điện dân dụng và công nghiệp."},
    {"title": "Năng lượng tái tạo", "description": "Phát triển các giải pháp điện mặt trời, điện gió và năng lượng sạch."},
    {"title": "Xây dựng", "description": "Thiết kế, thi công và quản lý chất lượng các công trình xây dựng."},
    {"title": "Kiến trúc", "description": "Thiết kế không gian, công trình và quy hoạch đô thị bền vững."},
    {"title": "Thiết kế nội thất", "description": "Thiết kế và hoàn thiện không gian sống, làm việc và thương mại."},
    {"title": "Quản lý dự án", "description": "Lập kế hoạch, điều phối nguồn lực và kiểm soát tiến độ dự án."},
    {"title": "Bất động sản", "description": "Phát triển, đầu tư, vận hành và môi giới tài sản bất động sản."},
    {"title": "Tài chính ngân hàng", "description": "Quản lý tài chính, tín dụng, đầu tư và dịch vụ ngân hàng."},
    {"title": "Kế toán kiểm toán", "description": "Ghi nhận tài chính, kiểm soát nội bộ và đảm bảo tính minh bạch."},
    {"title": "Bảo hiểm", "description": "Đánh giá rủi ro, phát triển sản phẩm và tư vấn bảo hiểm."},
    {"title": "Kinh doanh thương mại", "description": "Phát triển thị trường, bán hàng và quản trị hoạt động thương mại."},
    {"title": "Marketing", "description": "Nghiên cứu khách hàng, xây dựng thương hiệu và triển khai truyền thông."},
    {"title": "Thương mại điện tử", "description": "Vận hành nền tảng bán hàng trực tuyến và tối ưu trải nghiệm khách hàng."},
    {"title": "Logistics và chuỗi cung ứng", "description": "Quản lý vận tải, kho bãi, mua hàng và dòng chảy hàng hóa."},
    {"title": "Quản trị du lịch", "description": "Thiết kế, tổ chức và vận hành sản phẩm, dịch vụ du lịch."},
    {"title": "Quản trị khách sạn", "description": "Quản lý lưu trú, dịch vụ khách hàng và hoạt động khách sạn."},
    {"title": "Nhà hàng và ẩm thực", "description": "Chế biến món ăn, quản lý bếp và vận hành dịch vụ ăn uống."},
    {"title": "Luật", "description": "Tư vấn pháp lý, giải quyết tranh chấp và hỗ trợ tuân thủ."},
    {"title": "Hành chính và nhân sự", "description": "Tuyển dụng, phát triển con người và vận hành hành chính doanh nghiệp."},
    {"title": "Giáo dục và đào tạo", "description": "Giảng dạy, thiết kế chương trình và phát triển năng lực người học."},
    {"title": "Tâm lý học", "description": "Nghiên cứu hành vi và cung cấp hỗ trợ tâm lý cho cá nhân, cộng đồng."},
    {"title": "Công tác xã hội", "description": "Hỗ trợ nhóm yếu thế và triển khai các chương trình phát triển cộng đồng."},
    {"title": "Y khoa", "description": "Khám, chẩn đoán, điều trị và chăm sóc sức khỏe người bệnh."},
    {"title": "Dược học", "description": "Nghiên cứu, sản xuất, kiểm nghiệm và tư vấn sử dụng thuốc."},
    {"title": "Điều dưỡng", "description": "Theo dõi, chăm sóc và hỗ trợ phục hồi cho người bệnh."},
    {"title": "Kỹ thuật xét nghiệm y học", "description": "Thực hiện xét nghiệm phục vụ chẩn đoán và theo dõi điều trị."},
    {"title": "Dinh dưỡng", "description": "Đánh giá và xây dựng chế độ dinh dưỡng cho cá nhân, cộng đồng."},
    {"title": "Công nghệ sinh học", "description": "Ứng dụng sinh học trong y tế, nông nghiệp, thực phẩm và môi trường."},
    {"title": "Công nghệ thực phẩm", "description": "Nghiên cứu, sản xuất và kiểm soát chất lượng thực phẩm."},
    {"title": "Nông nghiệp công nghệ cao", "description": "Ứng dụng công nghệ để nâng cao năng suất và chất lượng nông nghiệp."},
    {"title": "Chăn nuôi và thú y", "description": "Chăm sóc vật nuôi, phòng trị bệnh và quản lý sản xuất chăn nuôi."},
    {"title": "Lâm nghiệp", "description": "Quản lý, bảo tồn và phát triển bền vững tài nguyên rừng."},
    {"title": "Khoa học môi trường", "description": "Đánh giá tác động và xây dựng giải pháp bảo vệ môi trường."},
    {"title": "Tài nguyên nước", "description": "Quản lý, khai thác và bảo vệ nguồn nước phục vụ phát triển."},
    {"title": "Địa chất và khoáng sản", "description": "Khảo sát địa chất, thăm dò và quản lý tài nguyên khoáng sản."},
    {"title": "Báo chí", "description": "Thu thập, kiểm chứng và truyền tải thông tin đến công chúng."},
    {"title": "Truyền thông đa phương tiện", "description": "Sản xuất nội dung số và triển khai truyền thông trên nhiều nền tảng."},
    {"title": "Sản xuất phim", "description": "Phát triển kịch bản, quay dựng và quản lý sản xuất nội dung điện ảnh."},
    {"title": "Thiết kế đồ họa", "description": "Sáng tạo hình ảnh, nhận diện thương hiệu và sản phẩm truyền thông."},
    {"title": "Thiết kế thời trang", "description": "Nghiên cứu xu hướng, thiết kế và phát triển sản phẩm thời trang."},
    {"title": "Âm nhạc và biểu diễn", "description": "Sáng tác, biểu diễn và sản xuất các sản phẩm nghệ thuật."},
    {"title": "Ngôn ngữ và biên phiên dịch", "description": "Sử dụng ngoại ngữ trong biên dịch, phiên dịch và giao tiếp chuyên môn."},
    {"title": "Quan hệ quốc tế", "description": "Nghiên cứu và hỗ trợ hợp tác giữa tổ chức, doanh nghiệp và quốc gia."},
    {"title": "Khoa học xã hội", "description": "Nghiên cứu con người, xã hội và các vấn đề phát triển cộng đồng."},
    {"title": "Nghiên cứu khoa học", "description": "Thiết kế nghiên cứu, thực nghiệm và công bố tri thức mới."},
    {"title": "Quản lý chất lượng", "description": "Xây dựng tiêu chuẩn, kiểm soát quy trình và cải tiến chất lượng."},
    {"title": "Quản lý sản xuất", "description": "Lập kế hoạch và tối ưu nguồn lực, năng suất trong nhà máy."},
    {"title": "Kỹ thuật hàng hải", "description": "Vận hành, bảo trì tàu biển và các hệ thống kỹ thuật hàng hải."},
    {"title": "Kinh tế hàng hải", "description": "Quản lý cảng biển, vận tải biển và hoạt động thương mại hàng hải."},
    {"title": "Kỹ thuật hàng không", "description": "Bảo dưỡng, sửa chữa và phát triển hệ thống kỹ thuật hàng không."},
    {"title": "Quản trị hàng không", "description": "Vận hành sân bay, hãng bay và các dịch vụ vận tải hàng không."},
    {"title": "Kỹ thuật đường sắt", "description": "Thiết kế, xây dựng và vận hành hạ tầng, phương tiện đường sắt."},
    {"title": "Giao thông vận tải", "description": "Quy hoạch, tổ chức và tối ưu hoạt động vận tải hành khách, hàng hóa."},
    {"title": "Quy hoạch đô thị", "description": "Lập quy hoạch không gian và hạ tầng cho đô thị phát triển bền vững."},
    {"title": "Quản lý đất đai", "description": "Đo đạc, đăng ký, định giá và quản lý sử dụng tài nguyên đất."},
    {"title": "Trắc địa và bản đồ", "description": "Đo đạc địa hình, xây dựng bản đồ và dữ liệu thông tin địa lý."},
    {"title": "Kỹ thuật thủy lợi", "description": "Thiết kế và quản lý công trình cấp thoát nước, phòng chống thiên tai."},
    {"title": "Kỹ thuật hóa học", "description": "Thiết kế và vận hành quy trình sản xuất hóa chất, vật liệu."},
    {"title": "Kỹ thuật vật liệu", "description": "Nghiên cứu, chế tạo và kiểm định vật liệu phục vụ sản xuất."},
    {"title": "Công nghệ dệt may", "description": "Thiết kế quy trình, sản xuất và kiểm soát chất lượng sản phẩm dệt may."},
    {"title": "Công nghệ da giày", "description": "Phát triển vật liệu, quy trình và sản phẩm trong ngành da giày."},
    {"title": "In ấn và xuất bản", "description": "Biên tập, thiết kế, sản xuất và phát hành các sản phẩm xuất bản."},
    {"title": "Khai thác mỏ", "description": "Thăm dò, khai thác và quản lý hoạt động sản xuất khoáng sản."},
    {"title": "Kỹ thuật dầu khí", "description": "Thăm dò, khai thác, chế biến và vận chuyển dầu khí."},
    {"title": "Kỹ thuật hạt nhân", "description": "Ứng dụng công nghệ hạt nhân trong năng lượng, y tế và công nghiệp."},
    {"title": "Vật lý học", "description": "Nghiên cứu các quy luật vật chất và ứng dụng trong khoa học, công nghệ."},
    {"title": "Toán học và thống kê", "description": "Xây dựng mô hình toán, phân tích thống kê và giải quyết bài toán định lượng."},
    {"title": "Hóa học", "description": "Nghiên cứu thành phần, tính chất và ứng dụng của các chất hóa học."},
    {"title": "Sinh học", "description": "Nghiên cứu sự sống, sinh vật và các hệ sinh thái."},
    {"title": "Hải dương học", "description": "Nghiên cứu biển, đại dương và quản lý tài nguyên môi trường biển."},
    {"title": "Khí tượng và khí hậu học", "description": "Quan trắc, dự báo thời tiết và nghiên cứu biến đổi khí hậu."},
    {"title": "Thiên văn học", "description": "Nghiên cứu các thiên thể, vũ trụ và công nghệ quan sát không gian."},
    {"title": "Khảo cổ học", "description": "Nghiên cứu quá khứ thông qua di tích, hiện vật và tư liệu khảo cổ."},
    {"title": "Lịch sử học", "description": "Nghiên cứu, giảng dạy và bảo tồn tri thức về lịch sử."},
    {"title": "Triết học", "description": "Nghiên cứu tư tưởng, đạo đức, nhận thức và các vấn đề nền tảng của xã hội."},
    {"title": "Văn học", "description": "Nghiên cứu, sáng tác, phê bình và giảng dạy các tác phẩm văn học."},
    {"title": "Thư viện và thông tin học", "description": "Tổ chức, quản lý và cung cấp tài nguyên thông tin cho người dùng."},
    {"title": "Văn thư lưu trữ", "description": "Quản lý văn bản, hồ sơ và bảo quản tài liệu lưu trữ."},
    {"title": "Bảo tàng học", "description": "Sưu tầm, bảo quản, nghiên cứu và trưng bày di sản văn hóa."},
    {"title": "Giáo dục mầm non", "description": "Chăm sóc và tổ chức hoạt động giáo dục cho trẻ nhỏ."},
    {"title": "Giáo dục tiểu học", "description": "Giảng dạy và phát triển nền tảng kiến thức, kỹ năng cho học sinh tiểu học."},
    {"title": "Sư phạm ngoại ngữ", "description": "Giảng dạy ngoại ngữ và thiết kế hoạt động phát triển năng lực ngôn ngữ."},
    {"title": "Sư phạm khoa học tự nhiên", "description": "Giảng dạy toán và khoa học theo định hướng thực hành, tích hợp STEM."},
    {"title": "Giáo dục đặc biệt", "description": "Thiết kế và thực hiện chương trình hỗ trợ người học có nhu cầu đặc biệt."},
    {"title": "Y tế công cộng", "description": "Phòng bệnh, giám sát dịch tễ và nâng cao sức khỏe cộng đồng."},
    {"title": "Phục hồi chức năng", "description": "Hỗ trợ người bệnh cải thiện vận động và khả năng sinh hoạt."},
    {"title": "Răng hàm mặt", "description": "Khám, điều trị và chăm sóc sức khỏe răng miệng."},
    {"title": "Kỹ thuật hình ảnh y học", "description": "Vận hành thiết bị chẩn đoán hình ảnh phục vụ khám chữa bệnh."},
    {"title": "Hộ sinh", "description": "Chăm sóc sức khỏe sinh sản, thai kỳ, sinh nở và trẻ sơ sinh."},
    {"title": "Quản lý bệnh viện", "description": "Tổ chức vận hành, tài chính và chất lượng dịch vụ tại cơ sở y tế."},
    {"title": "Thể dục thể thao", "description": "Nghiên cứu, tổ chức và phát triển hoạt động thể thao, vận động."},
    {"title": "Huấn luyện thể thao", "description": "Xây dựng giáo án và huấn luyện vận động viên, người tập luyện."},
    {"title": "Chăm sóc sắc đẹp", "description": "Cung cấp dịch vụ thẩm mỹ, chăm sóc da, tóc và sức khỏe sắc đẹp."},
    {"title": "Tổ chức sự kiện", "description": "Lập kế hoạch, sản xuất và điều phối các chương trình, sự kiện."},
    {"title": "Quan hệ công chúng", "description": "Xây dựng uy tín và quản lý quan hệ giữa tổ chức với công chúng."},
    {"title": "Quảng cáo", "description": "Sáng tạo và triển khai chiến dịch truyền thông quảng bá sản phẩm."},
    {"title": "Nghiên cứu thị trường", "description": "Thu thập, phân tích dữ liệu khách hàng và xu hướng thị trường."},
    {"title": "Quản trị bán lẻ", "description": "Vận hành cửa hàng, danh mục hàng hóa và trải nghiệm mua sắm."},
    {"title": "Xuất nhập khẩu", "description": "Thực hiện nghiệp vụ thương mại quốc tế, hải quan và giao nhận."},
    {"title": "Quản trị mua hàng", "description": "Tìm kiếm nhà cung cấp, đàm phán và quản lý hoạt động thu mua."},
    {"title": "Dịch vụ khách hàng", "description": "Hỗ trợ, giải quyết vấn đề và xây dựng trải nghiệm tích cực cho khách hàng."},
    {"title": "Tư vấn quản lý", "description": "Phân tích tổ chức và đề xuất giải pháp cải thiện hiệu quả kinh doanh."},
    {"title": "Khởi nghiệp và đổi mới sáng tạo", "description": "Phát triển mô hình kinh doanh mới và đưa ý tưởng sáng tạo ra thị trường."},
    {"title": "Thủ công mỹ nghệ", "description": "Thiết kế, chế tác và kinh doanh các sản phẩm thủ công có giá trị văn hóa."},
]

# The broadest grouping used by the existing demo Jobs below. Kept as a
# compatibility alias so the current job-posting demo remains unchanged.
SEED_CAREER = SEED_CAREERS[0]

# General/foundational skills attached directly to the Career (not any Job) —
# the beginner-posting fallback signal.
SEED_GENERAL_SKILLS = [
    "Toán học",
    "Giải quyết vấn đề",
    "Tư duy logic",
    "Nghiên cứu",
    "Viết báo cáo",
    "Giao tiếp",
    "Làm việc nhóm",
    "Tư duy phản biện",
]

# Specific job families ("nghe cu the") within the Career above.
SEED_JOBS = [
    {"title": "Backend Developer", "skills": ["Python", "SQL", "Docker"]},
    {"title": "Frontend Developer", "skills": ["JavaScript", "React"]},
    {"title": "Data Scientist", "skills": ["Python", "Machine Learning", "SQL"]},
    {"title": "DevOps Engineer", "skills": ["Docker", "Kubernetes", "AWS Cloud"]},
    {"title": "Business Analyst", "skills": ["Excel", "SQL", "English Communication"]},
]

# location: Ho Chi Minh City / Ha Noi have broad coverage; Da Nang and Can Tho
# each miss whole skill clusters on purpose, to demonstrate a regional gap.
SEED_JOB_POSTINGS = [
    # --- DevOps Engineer (Docker/Kubernetes/AWS Cloud) -> RISING: 2 previous, 6 recent ---
    {"title": "DevOps Engineer", "company": "CloudViet", "location": "Ho Chi Minh City", "days_ago": 50,
     "salary_min": 20_000_000, "salary_max": 30_000_000, "skills": ["Docker", "AWS Cloud"],
     "seniority_levels": ["MID"]},
    {"title": "SRE Engineer", "company": "TechCorp", "location": "Ha Noi", "days_ago": 35,
     "salary_min": 25_000_000, "salary_max": 35_000_000, "skills": ["Kubernetes", "Docker"],
     "seniority_levels": ["SENIOR"]},
    {"title": "DevOps Engineer", "company": "FinTechX", "location": "Ho Chi Minh City", "days_ago": 3,
     "salary_min": 22_000_000, "salary_max": 32_000_000, "skills": ["Docker", "Kubernetes", "AWS Cloud"],
     "seniority_levels": ["MID"],
     "requirements": "2+ nam kinh nghiem voi Docker/Kubernetes, hieu biet ve CI/CD.",
     "benefits": "Bao hiem suc khoe cao cap, lam viec hybrid, thuong hieu suat quy."},
    {"title": "Cloud Engineer", "company": "CloudViet", "location": "Ho Chi Minh City", "days_ago": 7,
     "salary_min": 20_000_000, "salary_max": 28_000_000, "skills": ["AWS Cloud", "Docker"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Site Reliability Engineer", "company": "TechCorp", "location": "Ha Noi", "days_ago": 10,
     "salary_min": 25_000_000, "salary_max": 38_000_000, "skills": ["Kubernetes", "Docker"],
     "seniority_levels": ["SENIOR"]},
    {"title": "DevOps Engineer", "company": "StartupY", "location": "Ha Noi", "days_ago": 14,
     "salary_min": 18_000_000, "salary_max": 26_000_000, "skills": ["Docker", "AWS Cloud"],
     "seniority_levels": ["MID"]},
    {"title": "Platform Engineer", "company": "FinTechX", "location": "Ho Chi Minh City", "days_ago": 18,
     "salary_min": 24_000_000, "salary_max": 34_000_000, "skills": ["Kubernetes", "AWS Cloud"],
     "seniority_levels": ["SENIOR"]},
    {"title": "DevOps Engineer", "company": "LogiTech", "location": "Ho Chi Minh City", "days_ago": 22,
     "salary_min": 20_000_000, "salary_max": 30_000_000, "skills": ["Docker", "Kubernetes"],
     "seniority_levels": ["MID"]},
    # Multi-level source ad ("Junior/Mid DevOps") — service fans this out into
    # 2 separate JobPosting rows (one per level) at ingest/seed time.
    {"title": "DevOps Engineer (Junior/Mid)", "company": "CloudViet", "location": "Da Nang", "days_ago": 2,
     "salary_min": 15_000_000, "salary_max": 25_000_000, "skills": ["Docker", "AWS Cloud"],
     "seniority_levels": ["JUNIOR", "MID"]},

    # --- Frontend Developer (JavaScript/React) -> DECLINING: 6 previous, 2 recent ---
    {"title": "Frontend Developer", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 32,
     "salary_min": 12_000_000, "salary_max": 18_000_000, "skills": ["JavaScript", "React"],
     "seniority_levels": ["MID"]},
    {"title": "React Developer", "company": "MediaVN", "location": "Ha Noi", "days_ago": 36,
     "salary_min": 14_000_000, "salary_max": 20_000_000, "skills": ["React", "JavaScript"],
     "seniority_levels": ["MID"]},
    {"title": "Frontend Engineer", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 40,
     "salary_min": 12_000_000, "salary_max": 17_000_000, "skills": ["JavaScript"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "UI Developer Intern", "company": "AdTech", "location": "Da Nang", "days_ago": 44,
     "salary_min": 10_000_000, "salary_max": 15_000_000, "skills": ["React"],
     "seniority_levels": ["INTERN"]},
    {"title": "Frontend Developer", "company": "MediaVN", "location": "Ha Noi", "days_ago": 48,
     "salary_min": 13_000_000, "salary_max": 19_000_000, "skills": ["JavaScript", "React"],
     "seniority_levels": ["MID"]},
    {"title": "Web Developer", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 55,
     "salary_min": 11_000_000, "salary_max": 16_000_000, "skills": ["JavaScript"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Frontend Developer", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 5,
     "salary_min": 12_000_000, "salary_max": 18_000_000, "skills": ["React", "JavaScript"],
     "seniority_levels": ["MID"],
     "requirements": "Thanh thao React va JavaScript ES6+, quen lam viec voi REST API.",
     "benefits": "Lam viec linh hoat, ho tro thiet bi, review luong 2 lan/nam."},
    {"title": "React Developer", "company": "AdTech", "location": "Da Nang", "days_ago": 15,
     "salary_min": 11_000_000, "salary_max": 16_000_000, "skills": ["React"],
     "seniority_levels": ["JUNIOR"]},

    # --- Backend Developer (Python/SQL/Docker) -> STABLE: 4 previous, 4 recent ---
    {"title": "Backend Developer", "company": "FinTechX", "location": "Ho Chi Minh City", "days_ago": 33,
     "salary_min": 18_000_000, "salary_max": 26_000_000, "skills": ["Python", "SQL"],
     "seniority_levels": ["MID"]},
    {"title": "Backend Engineer", "company": "LogiTech", "location": "Ho Chi Minh City", "days_ago": 38,
     "salary_min": 20_000_000, "salary_max": 28_000_000, "skills": ["Python", "Docker"],
     "seniority_levels": ["MID"]},
    {"title": "Software Engineer Manager", "company": "TechCorp", "location": "Ha Noi", "days_ago": 45,
     "salary_min": 19_000_000, "salary_max": 27_000_000, "skills": ["Python", "SQL", "Docker"],
     "seniority_levels": ["MANAGER"]},
    {"title": "Backend Developer", "company": "AgriData", "location": "Can Tho", "days_ago": 50,
     "salary_min": 14_000_000, "salary_max": 20_000_000, "skills": ["SQL", "Python"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Backend Developer", "company": "FinTechX", "location": "Ho Chi Minh City", "days_ago": 6,
     "salary_min": 19_000_000, "salary_max": 27_000_000, "skills": ["Python", "SQL"],
     "seniority_levels": ["MID"]},
    {"title": "Backend Engineer", "company": "LogiTech", "location": "Ho Chi Minh City", "days_ago": 12,
     "salary_min": 21_000_000, "salary_max": 29_000_000, "skills": ["Python", "Docker"],
     "seniority_levels": ["SENIOR"]},
    {"title": "Software Engineer", "company": "TechCorp", "location": "Ha Noi", "days_ago": 20,
     "salary_min": 20_000_000, "salary_max": 28_000_000, "skills": ["Python", "SQL"],
     "seniority_levels": ["MID"]},
    {"title": "Backend Developer Intern", "company": "AgriData", "location": "Can Tho", "days_ago": 26,
     "salary_min": 15_000_000, "salary_max": 21_000_000, "skills": ["SQL", "Python"],
     "seniority_levels": ["INTERN"]},

    # --- Data Scientist (Python/Machine Learning/SQL) -> RISING: 1 previous, 4 recent ---
    {"title": "Data Analyst", "company": "RetailPro", "location": "Ho Chi Minh City", "days_ago": 40,
     "salary_min": 16_000_000, "salary_max": 22_000_000, "skills": ["SQL", "Python"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Data Scientist", "company": "RetailPro", "location": "Ho Chi Minh City", "days_ago": 4,
     "salary_min": 25_000_000, "salary_max": 35_000_000, "skills": ["Python", "Machine Learning", "SQL"],
     "seniority_levels": ["SENIOR"]},
    {"title": "Machine Learning Engineer", "company": "FinTechX", "location": "Ho Chi Minh City", "days_ago": 9,
     "salary_min": 28_000_000, "salary_max": 40_000_000, "skills": ["Machine Learning", "Python"],
     "seniority_levels": ["SENIOR"],
     "requirements": "Kinh nghiem trien khai mo hinh ML vao production, thanh thao Python.",
     "benefits": "Luong canh tranh, ho tro hoc phi khoa hoc AI/ML, stock option."},
    {"title": "Data Scientist", "company": "TechCorp", "location": "Ha Noi", "days_ago": 16,
     "salary_min": 24_000_000, "salary_max": 33_000_000, "skills": ["Python", "SQL", "Machine Learning"],
     "seniority_levels": ["MID"]},
    {"title": "AI Engineer", "company": "StartupY", "location": "Ha Noi", "days_ago": 24,
     "salary_min": 26_000_000, "salary_max": 36_000_000, "skills": ["Machine Learning", "Python"],
     "seniority_levels": ["MID"]},

    # --- Business Analyst (Excel/SQL/English Communication) -> STABLE: 3 previous, 3 recent ---
    {"title": "Business Analyst", "company": "RetailPro", "location": "Ho Chi Minh City", "days_ago": 34,
     "salary_min": 15_000_000, "salary_max": 20_000_000, "skills": ["Excel", "SQL"],
     "seniority_levels": ["MID"]},
    {"title": "Business Analyst", "company": "AgriData", "location": "Can Tho", "days_ago": 42,
     "salary_min": 12_000_000, "salary_max": 16_000_000, "skills": ["Excel", "English Communication"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Data Analyst", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 52,
     "salary_min": 14_000_000, "salary_max": 19_000_000, "skills": ["Excel", "SQL", "English Communication"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Business Analyst", "company": "RetailPro", "location": "Ho Chi Minh City", "days_ago": 8,
     "salary_min": 15_000_000, "salary_max": 21_000_000, "skills": ["Excel", "SQL"],
     "seniority_levels": ["MID"]},
    {"title": "Business Analyst", "company": "AgriData", "location": "Can Tho", "days_ago": 17,
     "salary_min": 12_000_000, "salary_max": 17_000_000, "skills": ["English Communication", "Excel"],
     "seniority_levels": ["JUNIOR"]},
    {"title": "Data Analyst", "company": "ShopEase", "location": "Ho Chi Minh City", "days_ago": 27,
     "salary_min": 14_000_000, "salary_max": 20_000_000, "skills": ["Excel", "SQL", "English Communication"],
     "seniority_levels": ["MID"]},

    # --- Beginner postings: only general/foundational skills, no job-specific
    # technical skill -> job_id resolves to None, career_id still resolves via
    # the CareerSkill fallback (see MarketService._resolve_career_id_fallback). ---
    {"title": "Fresher Chuong Trinh Tap Su CNTT", "company": "TechCorp", "location": "Ha Noi", "days_ago": 5,
     "salary_min": 6_000_000, "salary_max": 9_000_000, "skills": ["Tư duy logic", "Giải quyết vấn đề"],
     "seniority_levels": ["INTERN"],
     "requirements": "Sinh vien nam cuoi/moi tot nghiep nganh CNTT, ham hoc hoi, khong yeu cau kinh nghiem.",
     "benefits": "Duoc dao tao bai ban 3 thang, co hoi len chinh thuc sau chuong trinh."},
    {"title": "Thuc Tap Sinh Cong Nghe", "company": "StartupY", "location": "Ho Chi Minh City", "days_ago": 11,
     "salary_min": 5_000_000, "salary_max": 8_000_000, "skills": ["Toán học", "Tư duy logic"],
     "seniority_levels": ["INTERN"]},
]

for _job in SEED_JOB_POSTINGS:
    _job.setdefault("description", f"{_job['title']} at {_job['company']} ({_job['location']}).")
