"""baseline schema

Revision ID: ba680aca4f7b
Revises: 
Create Date: 2026-07-18 13:15:50.902717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba680aca4f7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('market_trend', sa.Enum('RISING', 'STABLE', 'DECLINING', name='markettrend'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_title'), 'careers', ['title'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('education_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('UNIVERSITY', 'VOCATIONAL', 'SHORT_COURSE', name='pathtype'), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('requirements', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_paths_location'), 'education_paths', ['location'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('ai_inferred_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('career_skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'skill_id', name='uq_career_skill_requirement')
    )
    op.create_index(op.f('ix_career_skill_requirements_career_id'), 'career_skill_requirements', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_skill_requirements_skill_id'), 'career_skill_requirements', ['skill_id'], unique=False)
    op.create_table('career_skills',
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('career_id', 'skill_id')
    )
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('market_trend', sa.Enum('RISING', 'STABLE', 'DECLINING', name='markettrend'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_career_id'), 'jobs', ['career_id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=True)
    op.create_table('portfolio_share_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('share_with_business', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_share_settings_student_id'), 'portfolio_share_settings', ['student_id'], unique=True)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('reasoning_explanation', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['education_paths.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_career_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('gaps', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_career_recommendations_career_id'), 'student_career_recommendations', ['career_id'], unique=False)
    op.create_index(op.f('ix_student_career_recommendations_student_id'), 'student_career_recommendations', ['student_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=160), nullable=True),
    sa.Column('school_name', sa.String(length=160), nullable=True),
    sa.Column('education_level', sa.String(length=80), nullable=True),
    sa.Column('major', sa.String(length=160), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('interests', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_student_id'), 'student_profiles', ['student_id'], unique=True)
    op.create_table('student_skill',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'skill_id')
    )
    op.create_table('student_skill_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('source_service', sa.String(length=80), nullable=True),
    sa.Column('source_ref', sa.String(length=160), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level_delta', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_skill_events_skill_id'), 'student_skill_events', ['skill_id'], unique=False)
    op.create_index(op.f('ix_student_skill_events_student_id'), 'student_skill_events', ['student_id'], unique=False)
    op.create_table('student_skill_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'skill_id', name='uq_student_skill_profile')
    )
    op.create_index(op.f('ix_student_skill_profiles_skill_id'), 'student_skill_profiles', ['skill_id'], unique=False)
    op.create_index(op.f('ix_student_skill_profiles_student_id'), 'student_skill_profiles', ['student_id'], unique=False)
    op.create_table('task_builder_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('COLLECTING', 'READY', 'TASK_CREATED', name='conversationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('estimated_hours_min', sa.Integer(), nullable=False),
    sa.Column('estimated_hours_max', sa.Integer(), nullable=False),
    sa.Column('competency_points', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=4000), nullable=False),
    sa.Column('scope_included', sa.JSON(), nullable=False),
    sa.Column('scope_excluded', sa.JSON(), nullable=False),
    sa.Column('requires_auto_check', sa.Boolean(), nullable=False),
    sa.Column('requires_mentor_approval', sa.Boolean(), nullable=False),
    sa.Column('mentor_approval_sla_hours', sa.Integer(), nullable=True),
    sa.Column('data_privacy_notice', sa.String(length=2000), nullable=True),
    sa.Column('checkpoints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('complexity_level', sa.Enum('T1', 'T2', 'T3', name='taskcomplexity'), nullable=False),
    sa.Column('risk_level', sa.Enum('R0', 'R1', 'R2', 'R3', name='taskrisklevel'), nullable=False),
    sa.Column('target_evidence_level', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='evidencelevel'), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING_MENTOR_APPROVAL', 'APPROVED', 'REJECTED', 'NEED_MORE_INFO', name='taskreviewstatus'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_table('evidence_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.String(length=2000), nullable=False),
    sa.Column('observed_actions', sa.JSON(), nullable=False),
    sa.Column('evidence_sources', sa.JSON(), nullable=False),
    sa.Column('task_complexity', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('autonomy_level', sa.Enum('GUIDED', 'SEMI_INDEPENDENT', 'INDEPENDENT', name='autonomylevel'), nullable=False),
    sa.Column('proposed_skill_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('AI_DRAFT', 'STUDENT_REVIEWED', 'PENDING_MENTOR', 'VERIFIED', 'NEED_MORE_EVIDENCE', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('mentor_comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_claims_skill_id'), 'evidence_claims', ['skill_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_student_id'), 'evidence_claims', ['student_id'], unique=False)
    op.create_index(op.f('ix_evidence_claims_task_id'), 'evidence_claims', ['task_id'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('requirements', sa.String(length=2000), nullable=True),
    sa.Column('benefits', sa.String(length=2000), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('seniority_level', sa.Enum('INTERN', 'JUNIOR', 'MID', 'SENIOR', 'MANAGER', name='senioritylevel'), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_career_id'), 'job_postings', ['career_id'], unique=False)
    op.create_index(op.f('ix_job_postings_job_id'), 'job_postings', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_postings_location'), 'job_postings', ['location'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index(op.f('ix_job_postings_seniority_level'), 'job_postings', ['seniority_level'], unique=False)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_table('task_builder_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['task_builder_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_builder_documents_conversation_id'), 'task_builder_documents', ['conversation_id'], unique=False)
    op.create_table('task_builder_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('ENTERPRISE', 'AI', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('proposed_versions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['task_builder_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_builder_messages_conversation_id'), 'task_builder_messages', ['conversation_id'], unique=False)
    op.create_table('task_evaluation_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=500), nullable=False),
    sa.Column('weight_percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('input_type', sa.Enum('DATASET', 'DOCUMENT', 'OTHER', name='taskinputtype'), nullable=False),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PENDING_MENTOR_APPROVAL', 'APPROVED', 'REJECTED', 'NEED_MORE_INFO', name='taskreviewstatus'), nullable=False),
    sa.Column('approved_complexity', sa.Enum('T1', 'T2', 'T3', name='taskcomplexity'), nullable=True),
    sa.Column('approved_risk', sa.Enum('R0', 'R1', 'R2', 'R3', name='taskrisklevel'), nullable=True),
    sa.Column('approved_evidence_level', sa.Enum('L1', 'L2', 'L3', 'L4', 'L5', name='evidencelevel'), nullable=True),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_reviews_reviewer_id'), 'task_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_task_reviews_task_id'), 'task_reviews', ['task_id'], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('JOINED', 'SUBMITTED', 'AUTO_CHECK_PASSED', 'AUTO_CHECK_FAILED', 'MENTOR_APPROVED', 'MENTOR_REJECTED', 'COMPLETED', name='submissionstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('report_url', sa.String(length=1000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('student_reflection', sa.JSON(), nullable=True),
    sa.Column('auto_check_result', sa.JSON(), nullable=True),
    sa.Column('mentor_feedback', sa.String(length=2000), nullable=True),
    sa.Column('mentor_decision_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by', sa.Enum('AI', 'MENTOR', name='completionactor'), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submissions_student_id'), 'task_submissions', ['student_id'], unique=False)
    op.create_table('job_posting_skills',
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('job_posting_id', 'skill_id')
    )
    op.create_table('task_submission_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('scan_status', sa.Enum('PENDING', 'PASSED', 'FAILED', name='filescanstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['task_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_submission_files_submission_id'), 'task_submission_files', ['submission_id'], unique=False)
    op.create_table('task_submission_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.String(length=1000), nullable=True),
    sa.Column('scored_by', sa.Enum('AI', 'MENTOR', name='completionactor'), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['task_evaluation_criteria.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['task_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_submission_scores')
    op.drop_index(op.f('ix_task_submission_files_submission_id'), table_name='task_submission_files')
    op.drop_table('task_submission_files')
    op.drop_table('job_posting_skills')
    op.drop_index(op.f('ix_task_submissions_student_id'), table_name='task_submissions')
    op.drop_table('task_submissions')
    op.drop_index(op.f('ix_task_reviews_task_id'), table_name='task_reviews')
    op.drop_index(op.f('ix_task_reviews_reviewer_id'), table_name='task_reviews')
    op.drop_table('task_reviews')
    op.drop_table('task_outputs')
    op.drop_table('task_inputs')
    op.drop_table('task_evaluation_criteria')
    op.drop_index(op.f('ix_task_builder_messages_conversation_id'), table_name='task_builder_messages')
    op.drop_table('task_builder_messages')
    op.drop_index(op.f('ix_task_builder_documents_conversation_id'), table_name='task_builder_documents')
    op.drop_table('task_builder_documents')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_job_postings_seniority_level'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_location'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_job_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_career_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_evidence_claims_task_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_student_id'), table_name='evidence_claims')
    op.drop_index(op.f('ix_evidence_claims_skill_id'), table_name='evidence_claims')
    op.drop_table('evidence_claims')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('task_builder_conversations')
    op.drop_index(op.f('ix_student_skill_profiles_student_id'), table_name='student_skill_profiles')
    op.drop_index(op.f('ix_student_skill_profiles_skill_id'), table_name='student_skill_profiles')
    op.drop_table('student_skill_profiles')
    op.drop_index(op.f('ix_student_skill_events_student_id'), table_name='student_skill_events')
    op.drop_index(op.f('ix_student_skill_events_skill_id'), table_name='student_skill_events')
    op.drop_table('student_skill_events')
    op.drop_table('student_skill')
    op.drop_index(op.f('ix_student_profiles_student_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_student_career_recommendations_student_id'), table_name='student_career_recommendations')
    op.drop_index(op.f('ix_student_career_recommendations_career_id'), table_name='student_career_recommendations')
    op.drop_table('student_career_recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_portfolio_share_settings_student_id'), table_name='portfolio_share_settings')
    op.drop_table('portfolio_share_settings')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_career_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('interaction_logs')
    op.drop_table('career_skills')
    op.drop_index(op.f('ix_career_skill_requirements_skill_id'), table_name='career_skill_requirements')
    op.drop_index(op.f('ix_career_skill_requirements_career_id'), table_name='career_skill_requirements')
    op.drop_table('career_skill_requirements')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_education_paths_location'), table_name='education_paths')
    op.drop_table('education_paths')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_careers_title'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
